### ISSUE TITLE
Vanilla ore generation

### ISSUE THREAD

**Issue by tgstyle** [jriwanek/End-Metals#1]
I have disabled Orespawn standard ore generation, vanilla end ores still generate. There is no json to control them either, is this what is intended?

**Comment by cyanobacterium** [comment]
In vanilla Minecraft, there are no ores in the End. If you wish to prevent iron, coal, and gold from spawning in the End, your best bet is probably to remove them from the .json config file that specify End Metals ore spawning.

**Comment by tgstyle** [comment]
Those ores do not exist in the json. They spawn regardless.

**Comment by jriwanek** [comment]
@cyanobacterium End metals does infact add spawning of vanilla end metals, it currently does not use the orespawn library and thus is not configurable yet.

**Comment by jriwanek** [comment]
Additional: Orespawn is only used for BM metals and MM metals, we do vanilla metals internally (not orespawn) because orespawn wasn't out independantly at the time. (This allowed one unified version of nether metals/end metals for all three states. next release (1.9.4 only) will use orespawn for all three and thus the problem will be fixed.

**Comment by knoxhack** [comment]
Config file added for vanilla ores in version 1.0.3 of the 1.9 branch
